Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -21,6 +21,12 @@ jobs:
         cache: gradle
 
     - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
+      run: |
+    if [ -f ./gradlew ]; then
+      chmod +x ./gradlew
+    else
+      echo "gradlew not found!"
+      exit 1
+    fi
     - name: Build with Gradle
       run: ./gradlew build
